name: Deploy to Debian Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Debian server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /zaryadochka  # Change this to your app's directory
            git checkout main # Switch to main branch
            git pull origin main  # Pull the latest code
            go build # Build the application
            sudo systemctl restart zaryadochka.service  # Restart the service
